### ISSUE TITLE
unable to responde to existing comments

### ISSUE THREAD

**Issue by mariushuman** [proversity-org/cs_comments_service#16]
URL: 
http://staging.learn.proversity.io/courses/course-v1:nico+nico101+2017_T1/discussion/forum/
http://staging.learn.proversity.io/courses/course-v1:edX+DemoX+Demo_Course/discussion/forum/

Steps to reproduce the issue:

1. Login and select a course 
2. Select the Discussions tab
3. Select the Hamburger menu
4. Select a topic from the list
5. Select the drop down menu from 'Show all posts'
6. Select Show all posts,
7. Select a post and enter a comment

**Results:**
The user cannot add his comment and gets an error message

**Expected results:**
User is able add a comment and is visible to other users

**Comment by nicovanniekerk** [comment]
Indexes on forum needed to rebuild and not only initialized.
i have done the rebuild and looks like it is now working.

@mariushuman please re-test this and if you happy close it, or list the new errors.

**Comment by mariushuman** [comment]
@nicovanniekerk , it appears that I can now make comments and it is now saved.

Ticket can be closed
